# Generated by Django 4.1.4 on 2023-05-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_date_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='resume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Résumé'),
        ),
    ]
